[package]
name = "audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.5"
lstsq = "0.5.0"
nalgebra = "0.32.1"
typenum = "1.16.0"

[dev-dependencies]
fastrand = "1.9"
